#
# Core Provenance Library
#
# Copyright (c) Peter Macko
#

ROOT := ..


#
# Subprojects
#

LIBRARIES := platform-compat
PROGRAMS := standalone-test


#
# The test target
#

.PHONY: test

test: run


#
# Include the magic script
#

include $(ROOT)/make/project.mk

