#
# Core Provenance Library
#
# Copyright (c) Peter Macko
#

ROOT := ../../..


#
# Customize the build
#

PERL_MODULE_DEPENDECIES := ../CPLDirect



#
# Include the magic script
#

include $(ROOT)/make/perl-module.mk

