#
# Core Provenance Library
#
# Copyright (c) Peter Macko
#

ROOT := ../../..


#
# Customize the build
#

INSTALL := yes
DEPENDENCIES := ../../cpl.i $(ROOT)/include/cpl.h $(ROOT)/include/cplxx.h
CXXFLAGS := $(CXXFLAGS) -std=c++11

#
# Include the magic script
#

include $(ROOT)/make/python-module-swig.mk

