#
# Core Provenance Library
#
# Copyright (c) Peter Macko
#

ROOT := ../../..


#
# Customize the build
#

INSTALL := yes
JAVA_MODULE_DEPENDECIES := ../CPLDirect


#
# Include the magic script
#

include $(ROOT)/make/java-module.mk

