#
# Core Provenance Library
#
# Copyright (c) Peter Macko
#

ROOT := ../../..


#
# Customize the build
#

INSTALL := yes

MAVEN_INSTALL := yes
MAVEN_GROUP_ID := edu.harvard.pass
MAVEN_VERSION := 1.00

JAVA_MODULE_DEPENDECIES := ../CPLDirect


#
# Include the magic script
#

include $(ROOT)/make/java-module.mk

