#
# Core Provenance Library
#
# Copyright (c) Peter Macko
#

ROOT := ../../..


#
# Customize the build
#

INSTALL := yes
DEPENDENCIES := ../../cpl.i


#
# Include the magic script
#

include $(ROOT)/make/perl-module-swig.mk

