#
# Core Provenance Library
#
# Copyright (c) Peter Macko
#

ROOT := ../../..


#
# Customize the build
#

INSTALL := yes
PYTHON_MODULE_DEPENDECIES := ../CPLDirect


#
# Include the magic script
#

include $(ROOT)/make/python-module.mk

