#
# Core Provenance Library
#
# Copyright (c) Peter Macko
#

ROOT := ../..


#
# Subprojects
#

LIBRARIES := CPLDirect CPL
#PROGRAMS := test


#
# Include the magic script
#

include $(ROOT)/make/project.mk

