#
# Core Provenance Library
#
# Copyright (c) Peter Macko
#

ROOT :=..


#
# Customize the build
#

SHARED := yes
DEPENDENCIES := $(ROOT)/include/*.h
INCLUDE_FLAGS := $(INCLUDE_FLAGS) -I$(ROOT)/include


#
# Include the magic script
#

include ../make/library.mk

