# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpl_attach_r <- function() {
    invisible(.Call(CPL_cpl_attach_r))
}

import_document_json_r <- function(filename, originator, bundle_name, anchor_object, bundle_agent) {
    .Call(CPL_import_document_json_r, filename, originator, bundle_name, anchor_object, bundle_agent)
}

export_bundle_json_r <- function(bundle, path) {
    invisible(.Call(CPL_export_bundle_json_r, bundle, path))
}

cpl_detach_r <- function() {
    invisible(.Call(CPL_cpl_detach_r))
}

