# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpl_attach_r <- function() {
    invisible(.Call('CPL_cpl_attach_r', PACKAGE = 'CPL'))
}

import_document_json_r <- function(string, bundle_name) {
    .Call('CPL_import_document_json_r', PACKAGE = 'CPL', string, bundle_name)
}

export_bundle_json_r <- function(bundle, string) {
    invisible(.Call('CPL_export_bundle_json_r', PACKAGE = 'CPL', bundle, string))
}

cpl_detach_r <- function() {
    invisible(.Call('CPL_cpl_detach_r', PACKAGE = 'CPL'))
}

